# Generated by Django 5.2.1 on 2025-05-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_tickettype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tickettype",
            name="quantity",
        ),
        migrations.AddField(
            model_name="tickettype",
            name="quantity_sold",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tickettype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tickettype",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
