# Generated by Django 5.2.1 on 2025-05-29 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_remove_tickettype_quantity_tickettype_quantity_sold_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tickettype",
            name="updated_at",
        ),
    ]
