# Generated by Django 5.2.1 on 2025-05-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_remove_tickettype_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="title",
            new_name="name",
        ),
    ]
