backend:
  - changed-files:
      - any-glob-to-any-file:
          - backend/**

docs:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**
          - "*.md"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/workflows/**
          - .github/labeler.yml
          - .github/auto_assign.yml

devcontainer:
  - changed-files:
      - any-glob-to-any-file:
          - .devcontainer/**

docker:
  - changed-files:
      - any-glob-to-any-file:
          - compose.yml
          - compose.*.yml
          - .dockerignore

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - backend/pyproject.toml
          - backend/uv.lock
