labels:
  - label: features
    paths:
      - jobs/**
      - analytics/**

  - label: bugfix
    paths:
      - fixes/**
      - "**/bug_*"

  - label: docs
    paths:
      - "*.md"
      - docs/**

  - label: chore
    paths:
      - .github/**
      - .pre-commit-config.yaml

  - label: refactor
    paths:
      - "*/refactor_*"
