default_stages: [pre-commit]
# Ensure that the pre-commit can understand syntax
minimum_pre_commit_version: "4.6.0"

repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff lint
        # Using 'uv run' ensure it uses project's locked ruff version
        entry: uv run --project backend ruff check --config backend/pyproject.toml --fix
        language: system
        types_or: [python, pyi]

      - id: ruff-format
        name: ruff format
        entry: uv run --project backend ruff format --config backend/pyproject.toml --diff
        language: system
        types_or: [python, pyi]

      - id: docker-test
        name: docker-test
        # Check if inside dev container,
        # otherwise fall back to docker compose.
        entry: >
          bash -c '
          if [ -d "/workspace" ] || [ "$REMOTE_CONTAINERS" = "true" ]; then
            cd backend && uv run pytest --color=yes
          else
            docker compose run --rm -T web uv run pytest --color=yes
          fi
          '
        language: system
        stages: [pre-push]
        # Don't pass filenames to this hook since it runs tests on the whole codebase
        pass_filenames: false

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        name: codespell
        language: python
        # Use pyproject.toml for config
        additional_dependencies: ["toml"]
        files: \.(py|md|txt)$
