default_stages: [pre-commit]
# Ensure that the pre-commit can understand syntax
minimum_pre_commit_version: "4.6.0"

repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff lint
        # Using 'uv run' ensure it uses project's locked ruff version
        entry: uv run --project backend ruff check --config backend/pyproject.toml --fix
        language: system
        types_or: [python, pyi]

      - id: ruff-format
        name: ruff format
        entry: uv run --project backend ruff format --config backend/pyproject.toml --diff
        language: system
        types_or: [python, pyi]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        name: codespell
        language: python
        # Use pyproject.toml for config
        additional_dependencies: ["toml"]
        files: \.(py|md|txt)$

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version
    rev: 0.11.26
    hooks:
      # Make sure uv.lock is up to date even if pyproject.toml file was changed.
      - id: uv-lock
        args: ["--project=backend"]
        files: ^backend/pyproject.toml$
