services:
  web:
    build:
      target: production

    restart: unless-stopped

    ports:
      - "8000:8000"

    command: >
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      --workers 4

  db:
    restart: unless-stopped
