services:
  web:
    build:
      target: production

    restart: unless-stopped

    ports:
      - "8001:8000"

    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}

  db:
    # Replace with an external database service
    restart: unless-stopped
