services:
  web:
    build:
      context: ./backend
      target: development
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: ticketing_web
    environment:
      - DEBUG
      - SECRET_KEY
      - ALLOWED_HOSTS
      - DJANGO_SETTINGS_MODULE
    volumes:
      # Live code sync for development.
      - ./backend:/code
      # Tell Docker to hide the .venv directory from the host
      # Avoid confusion with the host's virtual environment
      - /code/.venv
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: ticketing_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"

volumes:
  postgres_data:
