[tool.black]
target-version = ['py313']
include = '\.py$'
exclude = '''
(?x)(
    /(\.venv|venv|build|dist|migrations|__pycache__)/
    | manage\.py$
    # | config/settings\.py$
)
'''

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["apps", "config"]
skip = ["migrations", "venv", ".venv"]
