name: "Auto Label PR"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label:
    permissions:
      # Allow the action to read the contents of the repository
      contents: read
      # Use labels in this repository
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v6
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
