name: "CI"

on:
  push:
    branches: [master, epic/**]
  pull_request:
    branches: [master, epic/**]

# Cancels duplicate workflow runs for the same ref and workflow name.
concurrency:
  group: "{{ github.workflow }}-{{ github.ref }}"
  cancel-in-progress: true

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          # Automatically caches uv's virtual environments
          enable-cache: true
          version: "0.11.27"

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --project backend --frozen --dev

      - name: Run pre-commit hooks
        run: uv run --project backend --frozen pre-commit run --all-files
