name: "Lint & Format Checks"

on:
  push:
    branches: [master, epic/**]
  pull_request:
    branches: [master, epic/**]

# Cancels duplicate workflow runs for the same ref and workflow name.
concurrency:
  group: "{{ github.workflow }}-{{ github.ref }}"
  cancel-in-progress: true

jobs:
  lint-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        # Set the working directory for all steps in this job
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          # Automatically caches uv's virtual environments
          enable-cache: true
          version: "0.11.21"

      - name: Set up Python
        run: uv python install

      - name: Run Ruff Lint
        run: uv run --frozen ruff check .
        working-directory: backend

      - name: Run Ruff Format
        run: uv run --frozen ruff format . --check
        working-directory: backend
