name: "Linting checks"

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image with cache
        run: |
          docker buildx create --use
          docker buildx build \
              --cache-from=type=local,src=/tmp/.buildx-cache \
              --cache-to=type=local,dest=/tmp/.buildx-cache \
              -f Dockerfile \
              -t app-test .

      - name: Start Docker Compose (build and run)
        run: |
          docker compose -f docker-compose.yml up -d

      - name: Wait for DB to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          for i in {1..10}; do
            docker compose run --rm web sh -c "python manage.py migrate > /dev/null 2>&1" && break
            echo "Retrying in 3 seconds..."
            sleep 3
          done
      - name: Run Django linters
        run: |
          docker compose run --rm web sh -c "
            flake8 . &&
            black . --check &&
            isort . --check-only
          "

      - name: Stop containers
        run: docker compose down
